

trigger:
- main

pool:
  default

stages:
- stage: Plan #name of the stage#
  jobs: 
  - job: terraformPlan #name of the job#
    steps: 
    - checkout: self
    - task: TerraformIstaller@1
      inputs:
        terraformVersion : 'latest'

    -task: TerraformCLI@2
     displayName: terraform initialize
     inputs:
      command: 'init'
           
         


