
trigger:
- main

pool:
  default

steps:

- checkout: self

- task: AzureResourceManagerTemplateDeployment@3

  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'newServiceConnection'
    subscriptionId: '40af5fd9-94c4-430a-9f3c-cf02ddd543ec'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RG_test'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/esha-assignment/ARM-Pipeline-Repo/blob/main/template.json'
    deploymentMode: 'Incremental'
    deploymentName: 'stgacc1'

