
trigger:
- main

pool:
  default

steps:

- script: |
    echo "Template File:"
    cat https://github.com/esha-assignment/ARM-Pipeline-Repo/blob/main/template.json
  displayName: "Verify Template and Parameter File Contents"

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'newServiceConnection'
    subscriptionId: '40af5fd9-94c4-430a-9f3c-cf02ddd543ec'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/esha-assignment/ARM-Pipeline-Repo/blob/main/template.json'
    deploymentMode: 'Incremental'
    deploymentName: 'stgacc_tst'